name: workflow

on: push 

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v5
      - name: instalar python
        run: pip install pytest
      - name: comprobar .py
        run: pytest test.py


