name: workflow

on: push 

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: ls -R
      - name: instalar python
        run: pip install pytest
      - name: comprobar .py
        run: pytest test.py
