name:  examen-workflow
on:
  push: 
    branches: ["nueva-caracteristica"]
jobs: 
  ejecicio1:
    runs-on: ubuntu-latest
    steps:
      - name: descarga de codigo
        uses: actions/checkout@v5
      - name: generacion de entorno
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: ejecutar la instalacion de pytest
        run: pip install pytest
      - name: comprobar codigo
        run: pytest test.py
      - name: construir imagen
        uses: docker/build-push-action@v6
